In [1]:
from gensim.models import Word2Vec

In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
import gensim

print(gensim.__version__)

4.4.0

In [4]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/DOB_ECB_Violations_20260929.csv"
)

df.head()

C:\Users\gimha_9pk7du7\AppData\Local\Temp\ipykernel_26260\1376370010.py:3: DtypeWarning: Columns (28: SECTION_LAW_DESCRIPTION3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,ISN_DOB_BIS_EXTRACT,ECB_VIOLATION_NUMBER,ECB_VIOLATION_STATUS,DOB_VIOLATION_NUMBER,BIN,BORO,BLOCK,LOT,HEARING_DATE,HEARING_TIME,...,SECTION_LAW_DESCRIPTION7,INFRACTION_CODE8,SECTION_LAW_DESCRIPTION8,INFRACTION_CODE9,SECTION_LAW_DESCRIPTION9,INFRACTION_CODE10,SECTION_LAW_DESCRIPTION10,AGGRAVATED_LEVEL,HEARING_STATUS,CERTIFICATION_STATUS
0,1729620,39156049P,ACTIVE,NaN,1003388.0,1,279.0,69.0,20270415,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,PENDING,NaN
1,1801198,39193627K,ACTIVE,NaN,5020516.0,5,795.0,41.0,20260902,930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,DEFAULT,NO COMPLIANCE RECORDED
2,1733211,39556132Z,RESOLVE,NaN,1063300.0,1,2135.0,60.0,20261029,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,CERTIFICATE ACCEPTED
3,1735317,35678949N,RESOLVE,04252024CDOEDM03,4190727.0,4,9155.0,25.0,20240820,1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,POP/IN-VIO,COMPLIANCE-INSP/DOC
4,1774496,39202758M,ACTIVE,NaN,3123714.0,3,5308.0,6.0,20261118,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,PENDING,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156749 entries, 0 to 156748
Data columns (total 46 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ISN_DOB_BIS_EXTRACT        156749 non-null  int64
 1   ECB_VIOLATION_NUMBER       156749 non-null  str
 2   ECB_VIOLATION_STATUS       156749 non-null  str
 3   DOB_VIOLATION_NUMBER       38177 non-null   str
 4   BIN                        156573 non-null  float64
 5   BORO                       156749 non-null  int64
 6   BLOCK                      155877 non-null  float64
 7   LOT                        155877 non-null  float64
 8   HEARING_DATE               156749 non-null  int64
 9   HEARING_TIME               156749 non-null  int64
 10  SERVED_DATE                156749 non-null  int64
 11  ISSUE_DATE                 156749 non-null  int64
 12  SEVERITY                   156749 non-null  str
 13  VIOLATION_TYPE             156749 non-null  str
 14  RESPONDENT_NAME            156637 non-null  str
 15  RESPONDENT_HOUSE_NUMBER    123534 non-null  str
 16  RESPONDENT_STREET          145898 non-null  str
 17  RESPONDENT_CITY            145300 non-null  str
 18  RESPONDENT_ZIP             144219 non-null  str
 19  VIOLATION_DESCRIPTION      156731 non-null  str
 20  PENALITY_IMPOSED           156749 non-null  str
 21  AMOUNT_PAID                156749 non-null  str
 22  BALANCE_DUE                156749 non-null  str
 23  INFRACTION_CODE1           156749 non-null  str
 24  SECTION_LAW_DESCRIPTION1   144871 non-null  str
 25  INFRACTION_CODE2           5626 non-null    str
 26  SECTION_LAW_DESCRIPTION2   4688 non-null    str
 27  INFRACTION_CODE3           26 non-null      float64
 28  SECTION_LAW_DESCRIPTION3   26 non-null      str
 29  INFRACTION_CODE4           0 non-null       float64
 30  SECTION_LAW_DESCRIPTION4   0 non-null       float64
 31  INFRACTION_CODE5           0 non-null       float64
 32  SECTION_LAW_DESCRIPTION5   0 non-null       float64
 33  INFRACTION_CODE6           0 non-null       float64
 34  SECTION_LAW_DESCRIPTION6   0 non-null       float64
 35  INFRACTION_CODE7           0 non-null       float64
 36  SECTION_LAW_DESCRIPTION7   0 non-null       float64
 37  INFRACTION_CODE8           0 non-null       float64
 38  SECTION_LAW_DESCRIPTION8   0 non-null       float64
 39  INFRACTION_CODE9           0 non-null       float64
 40  SECTION_LAW_DESCRIPTION9   0 non-null       float64
 41  INFRACTION_CODE10          0 non-null       float64
 42  SECTION_LAW_DESCRIPTION10  0 non-null       float64
 43  AGGRAVATED_LEVEL           156749 non-null  str
 44  HEARING_STATUS             146866 non-null  str
 45  CERTIFICATION_STATUS       119872 non-null  str
dtypes: float64(18), int64(6), str(22)
memory usage: 55.0 MB

In [7]:
df["VIOLATION_DESCRIPTION"].head()

0    TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...
1    UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...
2    3307.6.5.4 OBSERVED MULTIPLE LOCATIONS WHERE C...
3    FAILURE TO MAINTAIN BUILDING WALL(S) OR APPURT...
4    FAILURE TO COMPLY WITH THE COMMISSIONER'S ORDE...
Name: VIOLATION_DESCRIPTION, dtype: str

In [9]:
text_df = df[["VIOLATION_DESCRIPTION"]]

In [10]:
text_df.head()

                               VIOLATION_DESCRIPTION
0  TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...
1  UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...
2  3307.6.5.4 OBSERVED MULTIPLE LOCATIONS WHERE C...
3  FAILURE TO MAINTAIN BUILDING WALL(S) OR APPURT...
4  FAILURE TO COMPLY WITH THE COMMISSIONER'S ORDE...

In [12]:
df["VIOLATION_DESCRIPTION"].isna().sum()

np.int64(18)

In [13]:
text_df = text_df.dropna()

In [14]:
import re


def clean_text(text):

    text = text.lower()

    text = re.sub(
        r'[^a-z\s]',
        '',
        text
    )

    return text.split()

In [16]:
text_df["tokens"] = (
    text_df["VIOLATION_DESCRIPTION"]
    .apply(clean_text)
)

In [17]:
text_df.head()

,VIOLATION_DESCRIPTION,tokens
0,TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...,"[temp, construction, equipinstallation, on, si..."
1,UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...,"[unlawful, acts, failure, to, comply, with, co..."
2,3307.6.5.4 OBSERVED MULTIPLE LOCATIONS WHERE C...,"[observed, multiple, locations, where, constru..."
3,FAILURE TO MAINTAIN BUILDING WALL(S) OR APPURT...,"[failure, to, maintain, building, walls, or, a..."
4,FAILURE TO COMPLY WITH THE COMMISSIONER'S ORDE...,"[failure, to, comply, with, the, commissioners..."

In [19]:
import nltk

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gimha_9pk7du7\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in c:\users\gimha_9pk7du7\onedrive\desktop\projects\buildsafe-ai\.venv\lib\site-packages (from nltk) (0.7.1)
Collecting click (from nltk)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\gimha_9pk7du7\onedrive\desktop\projects\buildsafe-ai\.venv\lib\site-packages (from nltk) (1.6.0)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.29-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.6 kB ? eta -:--:--
     ------------------ ------------------- 20.5/41.6 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 41.6/41.6 kB 498.2 kB/s eta 0:00:00
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.4 kB ? eta -:--:--
     ----------------------------------- ---- 51.2/57.4 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 57.4/57.4 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: cloudpickle>=3.0 in c:\users\gimha_9pk7du7\onedrive\desktop\projects\buildsafe-ai\.venv\lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in c:\users\gimha_9pk7du7\onedrive\desktop\projects\buildsafe-ai\.venv\lib\site-packages (from tqdm->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   --- ------------------------------------ 0.2/1.8 MB 4.6 MB/s eta 0:00:01
   ------ --------------------------------- 0.3/1.8 MB 3.8 MB/s eta 0:00:01
   ---------- ----------------------------- 0.5/1.8 MB 3.8 MB/s eta 0:00:01
   ------------ --------------------------- 0.6/1.8 MB 3.2 MB/s eta 0:00:01
   ----------------- ---------------------- 0.8/1.8 MB 3.5 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.8 MB 3.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 3.3 MB/s eta 0:00:01
   ----------------------- ---------------- 1.1/1.8 MB 3.2 MB/s eta 0:00:01
   ------------------------- -------------- 1.2/1.8 MB 2.8 MB/s eta 0:00:01
   ------------------------------ --------- 1.4/1.8 MB 3.1 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  1.8/1.8 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.1 MB/s eta 0:00:00
Downloading regex-2026.9.29-cp311-cp311-win_amd64.whl (280 kB)
   ---------------------------------------- 0.0/280.6 kB ? eta -:--:--
   ------------------------ --------------- 174.1/280.6 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 280.6/280.6 kB 4.4 MB/s eta 0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.3 kB ? eta -:--:--
   ---------------------------------------- 125.3/125.3 kB 3.7 MB/s eta 0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
   ---------------------------------------- 0.0/80.2 kB ? eta -:--:--
   ----------------------------------- ---- 71.7/80.2 kB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 80.2/80.2 kB 896.9 kB/s eta 0:00:00
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.5.0 nltk-3.10.3 regex-2026.9.29 tqdm-4.70.1

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
from nltk.corpus import stopwords

In [21]:
stop_words = set(stopwords.words("english"))

In [22]:
print(list(stop_words)[:10])

['this', 'after', 'through', "shouldn't", "you'd", 'by', 'some', 'theirs', "mightn't", 'few']

In [23]:
def clean_text(text):

    text = text.lower()

    text = re.sub(
        r"[^a-z\s]",
        "",
        text
    )

    words = text.split()

    words = [
        word 
        for word in words 
        if word not in stop_words
    ]

    return words

In [24]:
text_df["tokens"] = (
    text_df["VIOLATION_DESCRIPTION"]
    .apply(clean_text)
)

In [25]:
text_df[["VIOLATION_DESCRIPTION","tokens"]].head()

,VIOLATION_DESCRIPTION,tokens
0,TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...,"[temp, construction, equipinstallation, site, ..."
1,UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...,"[unlawful, acts, failure, comply, commissioner..."
2,3307.6.5.4 OBSERVED MULTIPLE LOCATIONS WHERE C...,"[observed, multiple, locations, construction, ..."
3,FAILURE TO MAINTAIN BUILDING WALL(S) OR APPURT...,"[failure, maintain, building, walls, appurtena..."
4,FAILURE TO COMPLY WITH THE COMMISSIONER'S ORDE...,"[failure, comply, commissioners, order, file, ..."

In [26]:
Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5
)

In [27]:
text_df["tokens"].head()

0    [temp, construction, equipinstallation, site, ...
1    [unlawful, acts, failure, comply, commissioner...
2    [observed, multiple, locations, construction, ...
3    [failure, maintain, building, walls, appurtena...
4    [failure, comply, commissioners, order, file, ...
Name: tokens, dtype: object

In [28]:
empty_count = text_df["tokens"].apply(len).eq(0).sum()

print(empty_count)

1

In [29]:
all_words = [
    word
    for tokens in text_df["tokens"]
    for word in tokens
]

print("Total words:", len(all_words))
print("Unique words:", len(set(all_words)))

Total words: 3110876
Unique words: 59388

In [30]:
from gensim.models import Word2Vec


w2v_model = Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    seed=42
)

In [31]:
text_df.loc[
    text_df["tokens"].apply(len) == 0,
    "tokens"
] = [["unknown"]]

In [32]:
from collections import Counter

word_counts = Counter(
    word
    for tokens in text_df["tokens"]
    for word in tokens
)

word_counts.most_common(20)

[('observed', 80666),
 ('inspection', 60488),
 ('failure', 59459),
 ('building', 49760),
 ('time', 45927),
 ('permit', 40961),
 ('work', 36633),
 ('maintain', 31571),
 ('file', 27018),
 ('noted', 23891),
 ('floor', 21675),
 ('certificate', 20863),
 ('without', 20495),
 ('code', 19894),
 ('issued', 19738),
 ('exposure', 19026),
 ('construction', 18874),
 ('correction', 18850),
 ('comply', 18506),
 ('required', 18293)]

In [33]:
from gensim.models import Word2Vec


w2v_model = Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    seed=42
)

In [34]:
len(w2v_model.wv.index_to_key)

11260

In [35]:
w2v_model.wv["fire"]

array([ 2.0647528 , -3.2291267 , -1.6562407 , -1.5466987 , -1.4789846 ,
       -5.8567076 , -1.3166417 , -0.72176385, -0.5619066 , -0.9713294 ,
       -0.751626  , -1.1015626 ,  0.27213708, -1.6755217 ,  1.9124666 ,
       -4.4625545 ,  0.5742584 ,  0.21771136,  3.3740354 ,  1.5197386 ,
       -1.9207168 ,  0.4434109 ,  2.277084  , -0.61915463,  2.1723657 ,
       -2.9146419 ,  0.3671048 , -2.1196475 , -2.0281909 ,  0.80234516,
        1.1919955 ,  0.8194841 ,  1.1759883 , -2.7201684 ,  1.0992916 ,
        1.2773684 , -4.0344067 ,  0.67631954,  2.2413256 ,  1.9165205 ,
       -4.424801  ,  2.198908  , -1.5044969 ,  2.896182  ,  0.1277927 ,
       -3.6203754 , -1.1040128 ,  2.4730325 ,  2.1225414 ,  0.17249453,
       -1.8478165 ,  0.98531765,  1.2652401 ,  0.1270087 ,  1.50108   ,
        2.960609  , -0.98701835, -2.69547   ,  0.7393566 ,  0.82505065,
       -2.275179  , -0.39504188,  2.10474   ,  0.8538857 ,  1.2838129 ,
       -1.0020213 ,  0.8267576 , -0.12053453, -4.0562844 ,  1.1639693 ,
       -1.1182845 , -0.62387425, -0.27439067,  0.62949854,  0.04479818,
        0.9407535 ,  0.50909364, -0.03993607, -0.991091  ,  0.41149348,
        1.2882477 , -0.83764565,  2.0832534 ,  2.6168478 , -3.5726993 ,
       -0.6290137 ,  2.4178305 ,  1.5537883 ,  1.4104342 , -3.4630754 ,
       -1.4060469 , -0.30741236,  1.9621224 ,  2.082015  , -2.3760855 ,
       -1.1130894 ,  0.19234449,  0.71174926, -0.3775619 , -2.4521265 ],
      dtype=float32)

In [36]:
w2v_model.wv.most_similar("fire", topn=10)

[('hatches', 0.7236344218254089),
 ('windowfire', 0.5819328427314758),
 ('hatch', 0.5794876217842102),
 ('egressfire', 0.5301899313926697),
 ('nonfire', 0.5151681303977966),
 ('fir', 0.48158085346221924),
 ('landings', 0.4279305040836334),
 ('drop', 0.41003820300102234),
 ('resetting', 0.40329909324645996),
 ('inaudible', 0.3932740390300751)]

In [37]:
len(w2v_model.wv.index_to_key)

11260

In [38]:
w2v_model.wv.most_similar("fire", topn=10)

[('hatches', 0.7236344218254089),
 ('windowfire', 0.5819328427314758),
 ('hatch', 0.5794876217842102),
 ('egressfire', 0.5301899313926697),
 ('nonfire', 0.5151681303977966),
 ('fir', 0.48158085346221924),
 ('landings', 0.4279305040836334),
 ('drop', 0.41003820300102234),
 ('resetting', 0.40329909324645996),
 ('inaudible', 0.3932740390300751)]

In [39]:
w2v_model.wv.most_similar("building", topn=10)

[('bldg', 0.6732802987098694),
 ('buildings', 0.5882065296173096),
 ('house', 0.5740991234779358),
 ('premises', 0.5343278050422668),
 ('property', 0.5032336115837097),
 ('build', 0.4575945734977722),
 ('buildingi', 0.3932569921016693),
 ('yard', 0.37530651688575745),
 ('addition', 0.37256377935409546),
 ('inspection', 0.3672925531864166)]

In [ ]:
w2v_model.wv.most_similar("failure", topn=10)

[('failed', 0.5868493318557739),
 ('mannerfailure', 0.4325345754623413),
 ('ftm', 0.42180681228637695),
 ('reissuehfailure', 0.418378084897995),
 ('faiure', 0.41286155581474304),
 ('ftmb', 0.41195330023765564),
 ('maintain', 0.4018087387084961),
 ('failing', 0.4005565643310547),
 ('falure', 0.3937343955039978),
 ('thereof', 0.38866111636161804)]

: