In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/buildsafe_text_cleaned.csv")

df.shape

(102467, 28)

In [2]:
X = df.drop("SEVERITY", axis=1)

y = df["SEVERITY"]

In [3]:
categorical_features = [
    "VIOLATION_TYPE",
    "RESPONDENT_CITY",
    "RESPONDENT_ZIP",
    "INFRACTION_CODE1"
]

In [4]:
numerical_features = [
    "BORO",
    "BLOCK",
    "LOT",
    "ISSUE_YEAR",
    "ISSUE_MONTH",
    "ISSUE_DAY",
    "ISSUE_DAY_OF_WEEK",
    "ISSUE_QUARTER",
    "PREVIOUS_VIOLATION_COUNT",
    "PREVIOUS_CLASS1_COUNT",
    "PREVIOUS_CLASS2_COUNT",
    "PREVIOUS_CLASS3_COUNT"
]

In [5]:
X[categorical_features].isnull().sum()

VIOLATION_TYPE      0
RESPONDENT_CITY     0
RESPONDENT_ZIP      0
INFRACTION_CODE1    0
dtype: int64

In [6]:
from sklearn.preprocessing import OneHotEncoder


encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)


encoded_features = encoder.fit_transform(
    X[categorical_features]
)


encoded_features

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(102467, 3063))

In [7]:
encoded_df = pd.DataFrame(
    encoded_features,
    columns=encoder.get_feature_names_out(categorical_features)
)


encoded_df.head()

,VIOLATION_TYPE_Boilers,VIOLATION_TYPE_Construction,VIOLATION_TYPE_Cranes and Derricks,VIOLATION_TYPE_Elevators,VIOLATION_TYPE_Local Law,VIOLATION_TYPE_Plumbing,VIOLATION_TYPE_Public Assembly,VIOLATION_TYPE_Quality of Life,VIOLATION_TYPE_Signs,VIOLATION_TYPE_Site Safety,...,INFRACTION_CODE1_318,INFRACTION_CODE1_351,INFRACTION_CODE1_354,INFRACTION_CODE1_379,INFRACTION_CODE1_380,INFRACTION_CODE1_382,INFRACTION_CODE1_383,INFRACTION_CODE1_384,INFRACTION_CODE1_385,INFRACTION_CODE1_Z99
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
X_final = pd.concat(
    [
        X[numerical_features].reset_index(drop=True),
        encoded_df.reset_index(drop=True)
    ],
    axis=1
)


X_final.head()

,BORO,BLOCK,LOT,ISSUE_YEAR,ISSUE_MONTH,ISSUE_DAY,ISSUE_DAY_OF_WEEK,ISSUE_QUARTER,PREVIOUS_VIOLATION_COUNT,PREVIOUS_CLASS1_COUNT,...,INFRACTION_CODE1_318,INFRACTION_CODE1_351,INFRACTION_CODE1_354,INFRACTION_CODE1_379,INFRACTION_CODE1_380,INFRACTION_CODE1_382,INFRACTION_CODE1_383,INFRACTION_CODE1_384,INFRACTION_CODE1_385,INFRACTION_CODE1_Z99
0,1,800.0,71.0,2025,1,1,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2573.0,49.0,2025,1,1,2,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,5580.0,96.0,2025,1,2,3,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,1757.0,17.0,2025,1,2,3,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,1424.0,7503.0,2025,1,2,3,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
from sklearn.preprocessing import LabelEncoder


target_encoder = LabelEncoder()


y_encoded = target_encoder.fit_transform(y)


y_encoded[:10]

array([0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [10]:
target_mapping = dict(
    zip(
        target_encoder.classes_,
        target_encoder.transform(target_encoder.classes_)
    )
)


target_mapping

{'CLASS - 1': np.int64(0), 'CLASS - 2': np.int64(1), 'CLASS - 3': np.int64(2)}

In [11]:
print("Original features:", X.shape)

print("After encoding:", X_final.shape)

Original features: (102467, 27)
After encoding: (102467, 3075)

In [12]:
X_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 102467 entries, 0 to 102466
Columns: 3075 entries, BORO to INFRACTION_CODE1_Z99
dtypes: float64(3067), int64(6), str(2)
memory usage: 2.3 GB

In [14]:
import pickle


with open(
    "../notebooks/models/categorical_encoder.pkl",
    "wb"
) as f:
    pickle.dump(
        encoder,
        f
    )